const tailwindTypographyConfig = {
  theme: {
    fontFamily: {
      ScoreDream: ["S-CoreDream-3Light"],
      Pretendard: ["Pretendard-Regular"],
    },
  },
  plugins: [
    ({ addUtilities }) => {
      addUtilities({
        ".head-01-regular": {
          fontFamily: "SCoreDream",
          fontWeight: "200",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".head-01-bold": {
          fontFamily: "SCoreDream",
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".head-02-regular": {
          fontFamily: "SCoreDream",
          fontWeight: "200",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".head-02-bold": {
          fontFamily: "SCoreDream",
          fontWeight: "600",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".head-03-regular": {
          fontFamily: "SCoreDream",
          fontWeight: "200",
          fontSize: "24px",
          lineHeight: "32px",
          letterSpacing: "-0.25px",
        },
        ".head-03-bold": {
          fontFamily: "SCoreDream",
          fontWeight: "600",
          fontSize: "24px",
          lineHeight: "32px",
          letterSpacing: "-0.25px",
        },
        ".head-04-regular": {
          fontFamily: "SCoreDream",
          fontWeight: "200",
          fontSize: "28px",
          lineHeight: "36px",
          letterSpacing: "-0.25px",
        },
        ".head-04-bold": {
          fontFamily: "SCoreDream",
          fontWeight: "600",
          fontSize: "28px",
          lineHeight: "36px",
          letterSpacing: "-0.25px",
        },
        ".head-05-regular": {
          fontFamily: "SCoreDream",
          fontWeight: "200",
          fontSize: "32px",
          lineHeight: "40px",
          letterSpacing: "0px",
        },
        ".head-05-bold": {
          fontFamily: "SCoreDream",
          fontWeight: "600",
          fontSize: "32px",
          lineHeight: "40px",
          letterSpacing: "0px",
        },
        ".body-01-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.25px",
        },
        ".body-01-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.25px",
        },
        ".body-01-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.25px",
        },
        ".body-01-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-01-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-01-bold-compact": {
          fontFamily: "Pretendard",
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-02-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-02-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-02-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-02-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-02-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-02-bold-compact": {
          fontFamily: "Pretendard",
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".body-03-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "-0.5px",
        },
        ".body-03-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "-0.5px",
        },
        ".body-03-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "-0.5px",
        },
        ".body-03-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-03-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-03-bold-compact": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".body-04-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".body-04-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".body-04-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "18px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".body-04-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "22px",
          letterSpacing: "-0.5px",
        },
        ".body-04-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "22px",
          letterSpacing: "-0.5px",
        },
        ".body-04-bold-compact": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "18px",
          lineHeight: "22px",
          letterSpacing: "-0.5px",
        },
        ".body-05-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "28px",
          letterSpacing: "-0.5px",
        },
        ".body-05-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "28px",
          letterSpacing: "-0.5px",
        },
        ".body-05-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "20px",
          lineHeight: "28px",
          letterSpacing: "-0.5px",
        },
        ".body-05-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".body-05-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".body-05-bold-compact": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".label-01-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "14px",
          letterSpacing: "-0.25px",
        },
        ".label-01-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "14px",
          letterSpacing: "-0.25px",
        },
        ".label-01-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "12px",
          lineHeight: "14px",
          letterSpacing: "-0.25px",
        },
        ".label-02-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "16px",
          letterSpacing: "-0.5px",
        },
        ".label-02-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "16px",
          letterSpacing: "-0.5px",
        },
        ".label-02-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "14px",
          lineHeight: "16px",
          letterSpacing: "-0.5px",
        },
        ".label-03-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".label-03-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".label-03-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".label-04-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".label-04-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".label-04-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".label-05-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "24px",
          lineHeight: "30px",
          letterSpacing: "-0.5px",
        },
        ".label-05-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "24px",
          lineHeight: "30px",
          letterSpacing: "-0.5px",
        },
        ".label-05-bold": {
          fontFamily: "Pretendard",
          fontWeight: "600",
          fontSize: "24px",
          lineHeight: "30px",
          letterSpacing: "-0.5px",
        },
        ".helpertext-01-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "14px",
          letterSpacing: "-0.25px",
        },
        ".helpertext-01-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "14px",
          letterSpacing: "-0.25px",
        },
        ".helpertext-02-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "16px",
          letterSpacing: "-0.5px",
        },
        ".helpertext-02-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "16px",
          letterSpacing: "-0.5px",
        },
        ".link-01-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.25px",
        },
        ".link-01-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "12px",
          lineHeight: "18px",
          letterSpacing: "-0.25px",
        },
        ".link-02-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".link-02-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".link-02-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".link-02-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "14px",
          lineHeight: "18px",
          letterSpacing: "-0.5px",
        },
        ".link-03-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "-0.5px",
        },
        ".link-03-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "-0.5px",
        },
        ".link-03-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".link-03-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "16px",
          lineHeight: "20px",
          letterSpacing: "-0.5px",
        },
        ".link-04-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".link-04-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".link-04-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "18px",
          lineHeight: "22px",
          letterSpacing: "-0.5px",
        },
        ".link-04-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "18px",
          lineHeight: "22px",
          letterSpacing: "-0.5px",
        },
        ".link-05-regular": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "28px",
          letterSpacing: "-0.5px",
        },
        ".link-05-medium": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "28px",
          letterSpacing: "-0.5px",
        },
        ".link-05-regular-compact": {
          fontFamily: "Pretendard",
          fontWeight: "400",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
        ".link-05-medium-compact": {
          fontFamily: "Pretendard",
          fontWeight: "500",
          fontSize: "20px",
          lineHeight: "26px",
          letterSpacing: "-0.5px",
        },
      });
    },
  ],
};

export default tailwindTypographyConfig;
